name: acneia
description: AcnéIA – Détection d'acné et recommandations personnalisées
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase 
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  google_sign_in: ^6.2.1

  # Appwrite
  

  # HTTP
  dio: ^5.4.0

  # State Management
  flutter_bloc: ^8.1.4
  bloc: ^8.1.4
  equatable: ^2.0.5

  # Navigation
  go_router: ^12.1.3

  # UI
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_animate: ^4.3.0
  image_picker: ^1.0.7 
  flutter_staggered_animations: ^1.1.1
  percent_indicator: ^4.2.3
  fl_chart: ^0.66.1
  flutter_colorpicker: ^1.0.3
  badges: ^3.1.2
  timeago: ^3.6.1
  uuid: ^4.3.3

  # Utils
  shared_preferences: ^2.2.2
  intl: 0.20.2
  path_provider: ^2.1.2
  permission_handler: ^11.2.0

  # Icons
  iconsax: 0.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true